[package]
name = "marwood"
version = "1.0.0"
description = "Scheme R7RS Virtual Machine"
repository = "https://github.com/strtok/marwood"
authors = ["Erik Bremen <strtok@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
log = "0.4"
num = "0.4"
rand = "0.10"
thiserror = "2"
lazy_static = "1.5"

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "benchmark"
harness = false
